### ISSUE TITLE
Why not MPTC?

### ISSUE THREAD

**Issue by treeowl** [effectfully/sketches#2]
What's wrong with this?

```haskell
class (Monad b, Monad m, b ~ Unlift m) => MonadUnlift b m where
    type Unlift m :: * -> *
    withUnlift :: ((forall a. m a -> b a) -> b r) -> m r
```

There's very little you can *do* with your `MonadUnliftable` without bringing in `Unlift`, making for awkward type signatures. I guess it comes down to:

1. `MonadUnliftable`: slightly less redundancy in instance declarations.
2. `MonadUnlift`: no two-stage thinking about wanting `MonadUnlift` and therefore having to instantiate `MonadUnliftable`.

Personally, I don't find the redundancy too terrible.

**Comment by effectfully** [comment]
> What's wrong with this?

Nothing, I think I've just never seen such a thing and it didn't occur to me when I was writing the post. It's conceivable that some type synonym aggregating several classes might want to talk about `MonadUnliftable` rather than `MonadUnlift`, but that seems like a very rare use case and I agree that having a single class instead of a class + its instantiation is much nicer. I've included your suggestion in the post, thank you.
